// ฐานข้อมูล Supabase: ใช้ Publishable key เท่านั้น (ห้ามใส่ Secret key ในหน้าเว็บ)
window.ENVELOPE_APP_CONFIG = {
  supabaseUrl: "https://ywhuywtabxpunyuyjsou.supabase.co",
  supabasePublishableKey: "sb_publishable_xzzh_KY6bHtKjwXGQEle1A_ONRQF_wD",
  supabaseAdminEmail: "cpd.khonkaen01@gmail.com",
  supabaseRedirectUrl: "https://envelope-addressing.vercel.app/",
  layoutDefaultsVersion: "2026-07-22-envelope-layout-v3",
  sender: "สำนักงานสหกรณ์จังหวัดขอนแก่น",
  senderAddress: "เลขที่ 1/112 หมู่ที่ 13 ถนนหน้าเมือง ตำบลในเมือง\nอำเภอเมือง จังหวัดขอนแก่น 40000\nโทรศัพท์. 0-4324-6682 โทรสาร. 0-4324-6681",
  documentNumber: "ที่ ขก0010/.................................................................",
  paperSize: "DL",
  showSender: true,
  garudaImage: "assets/garuda.png",
  showGaruda: false,
  garudaPlacement: "left",
  garudaSizeMm: 15,
  senderTopMm: 10,
  senderLeftMm: 10,
  senderTextOffsetMm: 8,
  senderFontPt: 14,
  senderLineHeight: 1.2,
  recipientFontPt: 16,
  recipientTopPercent: 45,
  recipientLeftPercent: 35,
  recipientLineHeight: 1,
  showRecipientDepartment: false,
  showRecipientAddress: true,
  showPostagePermit: true,
  postagePermitText: "ชำระค่าฝากส่งเป็นรายเดือน\nใบอนุญาตเลขที่ xx/xxx\nไปรษณีย์เดชาวุธ",
  postagePermitTopMm: 10,
  postagePermitRightMm: 10,
  postagePermitFontPt: 10,
  postagePermitLineHeight: 1.2,
  paperLayouts: {
    DL: {
      garudaPlacement: "left",
      garudaSizeMm: 15,
      senderTopMm: 10,
      senderLeftMm: 10,
      senderTextOffsetMm: 8,
      senderFontPt: 14,
      senderLineHeight: 1.2,
      recipientFontPt: 16,
      recipientTopPercent: 45,
      recipientLeftPercent: 35,
      recipientLineHeight: 1,
      postagePermitTopMm: 10,
      postagePermitRightMm: 10,
      postagePermitFontPt: 10,
      postagePermitLineHeight: 1.2,
    },
    C5: {
      garudaPlacement: "left",
      garudaSizeMm: 15,
      senderTopMm: 10,
      senderLeftMm: 10,
      senderTextOffsetMm: 8,
      senderFontPt: 14,
      senderLineHeight: 1.2,
      recipientFontPt: 18,
      recipientTopPercent: 45,
      recipientLeftPercent: 35,
      recipientLineHeight: 1,
      postagePermitTopMm: 10,
      postagePermitRightMm: 10,
      postagePermitFontPt: 10,
      postagePermitLineHeight: 1.2,
    },
    A4L: {
      garudaPlacement: "left",
      garudaSizeMm: 15,
      senderTopMm: 10,
      senderLeftMm: 15,
      senderTextOffsetMm: 8,
      senderFontPt: 14,
      senderLineHeight: 1.2,
      recipientFontPt: 18,
      recipientTopPercent: 45,
      recipientLeftPercent: 35,
      recipientLineHeight: 1.2,
      postagePermitTopMm: 10,
      postagePermitRightMm: 10,
      postagePermitFontPt: 10,
      postagePermitLineHeight: 1.2,
    },
  },
};
