// ฐานข้อมูล Supabase: ใช้ Publishable key เท่านั้น (ห้ามใส่ Secret key ในหน้าเว็บ)
window.ENVELOPE_APP_CONFIG = {
  supabaseUrl: "https://ywhuywtabxpunyuyjsou.supabase.co",
  supabasePublishableKey: "sb_publishable_xzzh_KY6bHtKjwXGQEle1A_ONRQF_wD",
  supabaseAdminEmail: "cpd.khonkaen01@gmail.com",
  supabaseRedirectUrl: "https://envelope-addressing.vercel.app/",
  sender: "สำนักงานสหกรณ์จังหวัดขอนแก่น",
  senderAddress: "เลขที่ 1/112 หมู่ที่ 13 ถนนหน้าเมือง ตำบลในเมือง\nอำเภอเมือง จังหวัดขอนแก่น 40000\nโทรศัพท์. 0-4324-6682 โทรสาร. 0-4324-6681",
  documentNumber: "ที่ ขก0010/.................................................................",
  paperSize: "DL",
  showSender: true,
  garudaImage: "assets/garuda.png",
  showGaruda: true,
  garudaPlacement: "left",
  garudaSizeMm: 15,
  senderTopMm: 6,
  senderLeftMm: 14,
  senderTextOffsetMm: 10,
  senderFontPt: 9.5,
  senderLineHeight: 1.45,
  recipientFontPt: 12,
  recipientTopPercent: 40,
  recipientLeftPercent: 42,
  recipientLineHeight: 1.5,
  showRecipientDepartment: true,
  showRecipientAddress: true,
  showPostagePermit: true,
  postagePermitText: "ชำระค่าฝากส่งเป็นรายเดือน\nใบอนุญาตเลขที่ xx/xxx\nไปรษณีย์เดชาวุธ",
  postagePermitTopMm: 7,
  postagePermitRightMm: 8,
  postagePermitFontPt: 8.5,
  postagePermitLineHeight: 1.15,
};
